### PR TITLE
Fix repeated task

### PR DESCRIPTION
**Pull request by alcpereira**

### CODE REVIEW

**Comment by labrocadabro** [comment]
It's not a mistake. Leon asked us to do this review 3 times.

**Comment by labrocadabro** [comment]
i updated the wording of the item to try and make it a little clearer

**Comment by labrocadabro** [comment]
Oh I'm so sorry! I misread your code and didn't realize there actually *was* a repeated task.

**Comment by alcpereira** [comment]
Np. Should we update the id/name? I think it will impact a bit the LocalStorage.

**Pull request closed without merging**
