### PR TITLE
Closes #9

### LINKED ISSUE #9: Homework for class 29 is missing
**Hey hey! The tracker says there's no homework for class 29, but I just finished watching the VOD and there's actually a fair bit of homework!**
**He wants us to:**

- Do something with the pokemon API (there's a folder that's specifically set up for that in the materials folder for this class)
- Watch Object-oriented Programming in Javascript: Made Super Simple (https://www.youtube.com/watch?v=PFmuCDHHpwk)
- Read/Do the JS way chapter 09 - https://github.com/thejsway/thejsway/blob/master/manuscript/chapter09.md

**Push:**

- -Read/Do Eloquent JS chapter 06

--
here is the link to the specific slide with the homework, and a screenshot from it.
https://slides.com/leonnoel/100devs2-javascript-review-back-from-break#/66
image

Currently, the readings are listed as being assigned during class 30, but he actually assigns them in this class. : )
and there's no mention of the OOP video or the pokemon hw!

If you agree that this is something that needs fixing, I'd be happy to do it, if you'd be ammenable. Would be a great way for me to get some practice in, and hopefully helpful to take something off your plate!

### PR DESCRIPTION
**Pull request by brian926**
Closes #9 
Added class 29 to the index.html!

I got the homework and links directly from the Discord server under the follow-along-materials. There didn't seem to be anything for the Pokemon API though.

### CODE REVIEW

**Comment by labrocadabro** [comment]
Thank you! I apologize for the long delay in getting to this, I should have attended to it much sooner.

I did a search in the follow-along materials and the Pokemon API was never part of the homework as far as I can tell.

I don't want to rob you of your merged PR, but I took a look at it appears the problem is that the class 30 homework was actually assigned in class 29 and there are a few missing items.  This means your PR won't work as is. I'm listing the changes needed below, if you'd rather not make them, let me know and I'll do the edits myself.

In order to merge this successfully it needs a few changes:

1) Don't add a new entry for class 29.

2) Instead of adding a new entry for class 29, change class 30 like this:

				<tr class="hw30">
					<td>30</td>
					<td>32</td>

becomes

				<tr class="hw30">
					<td>29</td>
					<td>32</td>

3) Some of the assigned items are already present in class 30, leave them as is and  just add the missing items to the end of the list. 

This will allow anyone who has already checked off the existing items to keep their progress.

Thank you again! :)

**Review by labrocadabro — COMMENTED** [review]
1) Don't add a new entry for class 29.

2) Instead of adding a new entry for class 29, change class 30 like this:

     		<tr class="hw30">
     			<td>30</td>
     			<td>32</td>

becomes

			<tr class="hw30">
				<td>29</td>
				<td>32</td>

3)  Some of the assigned items are already present in class 30, leave them as is and just add the missing items to the end of the list.

**Comment by brian926** [comment]
Not a problem at all! Made the necessary changes, let me know if you see anything can I should fix!

**Comment by labrocadabro** [comment]
Just a little bit more, sorry! The new items need to reference hw30 class instead of hw29 (so they'll be correctly connected to the 'completed' logic). And adding the link to codewars is a good idea, but please use the existing 'hw30-2' class as it actually is the same item (and some people may have already marked it off).

**Comment by brian926** [comment]
Completely missed those in the links!! Sorry about that, should be all set now!

**Review by labrocadabro — APPROVED** [review]

**Pull request merged**
